---
- name: Converge to a Postfix server that has the role defaults set.
  hosts: all

  tasks:
    - name: "Set ansible_fqdn and ansible_domain something static for the tests"
      ansible.builtin.set_fact:
        ansible_fqdn: mail.test
        ansible_domain: test

    - name: "Include unibe_idsys.postfix"
      ansible.builtin.include_role:
        name: "unibe_idsys.postfix"
