---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true

    - name: Postfix service is running
      ansible.builtin.wait_for:
        port: 25
        timeout: 30
      register: port_check
      failed_when: port_check.failed

    - name: No mail alias for user root
      ansible.builtin.lineinfile:
        path: /etc/aliases
        regexp: "^root:"
        state: absent
      check_mode: true
      register: aliases
      failed_when: aliases is changed
