name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v6

      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install test dependencies.
        run: pip3 install -r requirements.txt

      - name: Lint code.
        run: |
          set -e
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    # See https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#using-a-matrix-strategy
    strategy:
      matrix:
        distro: [ubuntu2204, ubuntu2404]
        scenario: [default, local, lookup-tables, uninstall]
        include:
          - playbook: converge.yml

    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v6

      - name: Setup Python 3
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install test dependencies.
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests.
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
